#define ONFRONTCONNECTED 0
#define ONFRONTDISCONNECTED 1
#define ONRSPDEPTHMARKETDATASUBSCRIBE 2
#define ONRSPDEPTHMARKETDATACANCEL 3
#define ONRTNDEPTHMARKETDATA 4
#define ONRSPFORQUOTESUBSCRIBE 5
#define ONRSPFORQUOTECANCEL 6
#define ONRTNFORQUOTE 7
